### ISSUE TITLE
Error in Bioc devel workflow

### ISSUE THREAD

**Issue by TuomasBorman** [neurogenomics/rworkflows#125]
Hello!

I am currently [submitting `MgnifyR` package to Bioconductor](https://github.com/Bioconductor/Contributions/issues/3191). We are planning to start using `rworkflows` in our packages to standardize GHA.

The rworkflow does not got through because of dependency installation problems. The Ubuntu workflow should go through since it uses Bioc devel.

Here is the PR in MgnifyR package: https://github.com/EBI-Metagenomics/MGnifyR/pull/26
Here is the rworkflow file: https://github.com/EBI-Metagenomics/MGnifyR/blob/96b4def4e56ded818b75e5bf6868d208a8261fef/.github/workflows/rworkflows.yml

The problem:

1. Since the MgnifyR package is new on Bioc, it should depend on devel R which is 4.4.0 (rworkflow with R 4.3.0 was working).

2. There are some dependency R packages that need to be installed. However, there is a problem with installation, and build of the package fails. `ERROR: dependencies ‘mia’, ‘MultiAssayExperiment’, ‘TreeSummarizedExperiment’, ‘SummarizedExperiment’, ‘biomformat’ are not available for package ‘MGnifyR’`

3. I investigated [the log file](https://github.com/EBI-Metagenomics/MGnifyR/actions/runs/7525527288/job/20482015243) and it seems that there is a problem in installing undirect dependency R packages `rhdf5` and `S4Arrays`. I believe this is causing the problem. They cannot be compiled:

```
2024-01-14T16:16:53.1748981Z make: *** [/usr/local/lib/R/etc/Makeconf:191: H5E.o] Error 1
2024-01-14T16:16:53.1759878Z ERROR: compilation failed for package ‘rhdf5’
```

```
2024-01-14T16:25:04.6024946Z make: *** [/usr/local/lib/R/etc/Makeconf:191: array_selection.o] Error 1
2024-01-14T16:19:43.7586560Z ERROR: compilation failed for package ‘S4Arrays’
```

However, their build in devel Bioconductor seems to be OK:  [S4Arrays](https://bioconductor.org/packages/devel/bioc/html/S4Arrays.html) & [rhdf5]( https://bioconductor.org/packages/devel/bioc/html/rhdf5.html) 

4. Is the system lacking certain dependency which should be installed?

BR,
Tuomas Borman

**Comment by bschilder** [comment]
Hi @TuomasBorman, 

Thanks for using `rworkflows`! Apologies for the delay, I just got back from holiday. 

I noticed something similar with `rlang` not too long ago (only on ubuntu-devel though), but that has since resolved itself.

@grimbough is this something you've noticed as well?

**Comment by TuomasBorman** [comment]
I ran the workflow again, and now it seems that it goes through (there is another error not related to rworkflow). So I think everything is good now.

Thanks for nice package! There are also other packages where want to start using rworkflows.

**Comment by bschilder** [comment]
This is great to hear @TuomasBorman ! Debugging these sorts of things on GHA can be a bit tricky, as it's not always clear when errors are due to issues with GitHub's runners, system deps, R deps, the rworkflows action, or the R package itself. I'm currently working on ways to better disentangle these scenarios with interactive debugging #103 and will hopefully be able to release those features in the near future.

Glad to hear you're planning to make use of rworkflows more! Let me know if you need help with anything else.

All the best, 
Brian

**Comment by grimbough** [comment]
For some context, I think this was related to `Rf_errorcall` and similar functions that were updated in the R source a few weeks ago (https://github.com/wch/r-source/commit/360aeff9fc2ea3def1b0370c16239570fac6bdfc).  I interface has changed slightly and a bunch of packages stopped compiling, including `rhdf5 and `S4Arrays`.

We've been gradually going through packages and patching the problematic code e.g. https://github.com/grimbough/rhdf5/commit/069b1d8f30438d5aa2303476e740fb936cdde8de

The build system didn't report it, because while it's using R-devel, it's a version before those changes were introduced.  Anythign using GHA or the Bioc-devel docker image were getting the updated R-devel and running into the issue.

**Comment by bschilder** [comment]
Thanks so much for the insight @grimbough ! Glad to have this documented here in case it pops up again.
