### ISSUE TITLE
fail early if PAT_GITHUB secret unavailable?

### ISSUE THREAD

**Issue by vjcitn** [neurogenomics/rworkflows#55]
**Is your feature request related to a problem? Please describe.**

I am not sure but it seems to me that if a package repo lacks the secret `PAT_GITHUB`,
this
```
Run JamesIves/github-pages-deploy-action@releases/v4
```
will fail, after considerable efforts building and checking.

**Describe the solution you'd like**
Exit action unless the secret is found.

**Describe alternatives you've considered**
Setting and rerunning has worked.

**Additional context**
 Line 6250 [here](https://github.com/vjcitn/BiocHail/actions/runs/4330488440/jobs/7564106251) shows
````
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Notice: Deployment failed! ❌
```

**Comment by bschilder** [comment]
Hi @vjcitn , that's actually the expected behaviour:
https://github.com/neurogenomics/rworkflows#github-secrets

You need a GitHub token for lots of GHA-related processes, including this step.
By default, it looks for a token called `PAT_GITHUB`, but you can customise this with the `github_token` arg when making your workflow file:
```R
rworkflows::use_workflow(github_token = )
```

Just a side note, the reason it's named `PAT_GITHUB`  (as opposed to `GITHUB_PAT`) is because GitHub doesn't let you created tokens that start with the substring "GITHUB*"
