### ISSUE TITLE
Relevance of using AnVIL

### ISSUE THREAD

**Issue by js2264** [neurogenomics/rworkflows#58]
Hi @bschilder, 

The AnVIL repository is currently never being used, as the dependencies install pass 1 systematically fails because of a missing bracket (see my PR #57). 
That being said, the AnVIL repository is currently hard-coded to " https://bioconductordocker.blob.core.windows.net/packages/3.16/bioc". Is this the expected behavior? In my matrix config, if I have `bioc: release` (currently `3.17`), am I right to assume that the first pass will not manage to install any package? Should there be an automated way to set this URL?

Best, Jacques

**Comment by bschilder** [comment]
Hi @js2264, thanks so much for pointing this out and making the PR. I hadn't realized the issue about the bracket, I'll merge that PR right away.

Regarding AnVIL, I think I had a version of this that dynamically created the URL based on the relevant version of Bioc. But i must have accidentally replaced this with an old hard-coded version at some point (probably when I switched back from using the `r-lib` action #52 ). I'll make a fix to ensure the right version of Bioc is being used.

That said, something I'm a bit unclear on is whether this approach of specifying the AnVIL URL offers any benefit atm (as opposed to just using `BiocManager` with the defaults), since `BiocManager` automatically should use pre-compiled binaries. This step originally comes from `biocthis`. @lcolladotor do you have any thoughts on this?

**Comment by bschilder** [comment]
I just confirmed that the URL no longer seems to be valid. `rworkflows` uses the same link that `biocthis` does:
https://bioconductordocker.blob.core.windows.net/packages/3.16/bioc
https://github.com/lcolladotor/biocthis/blob/910b96b140505ac9b13cc46a09be4b2d40d2ef75/.github/workflows/check-bioc.yml#L179
<img width="1146" alt="Screenshot 2023-05-05 at 12 32 52" src="https://user-images.githubusercontent.com/34280215/236515466-8a76d99e-cfd3-4623-a693-89ad5b410790.png">

Modifying the URL to use 3.17 has the same issue:
https://bioconductordocker.blob.core.windows.net/packages/3.17/bioc

**Comment by bschilder** [comment]
Just confirmed with @LiNk-NY offline; supplying the `AnVIL` URL explicitly is no longer necessary (or useful) bc `BiocManager` installs pre-compiled binaries by default.

Just pushed some changes in `rworkflows` to reflect this @js2264 .
